### ISSUE TITLE
Xgboost in brt section

### ISSUE THREAD

**Issue by timcdlucas** [zoonproject/zoontutorials#30]
I assume we're allowed to jump in here and start suggesting stuff. Are we also allowed to make direct contributions?

Anyway, i think I'd like to see mention of xgboost in `MachineLearn` in the brt section. It's the cutting edge and is used in all the kaggle competitions.

**Comment by timcdlucas** [comment]
Ps great work so far on this.

**Comment by goldingn** [comment]
Of course! Please suggest and contribute as much as you want!

I'd not seen Xgboost before - it's just a better implementation of pretty much the same model, right? Yeah, definitely a sentence or two at the end of that section (any more might scare people off). How about something like this @Doi90?:

> The [`XGBoost`]() software for fitting BRTs is increasingly used in machine learning applications to really big datasets. You can use the `MachineLearn` module to fit BRT models with XGBoost by replacing the model module above with: `MachineLearn(method = 'xgbTree')`.

**Comment by Doi90** [comment]
I'm sure I could manage that. I hadn't even noticed that MachineLearn module. I'll have to have a look and see how it compares using `MachineLearn` for some of the models we're considering vs the single model modules like `RandomForest`

**Comment by timcdlucas** [comment]
Yeah basically same model. Few more options. Cleverly parallelized. Not that people often use millions of rows in SDM.

And yes was thinking a single sentence like the one above.
