### ISSUE TITLE
rebuilding local repos and forks after rebase

### ISSUE THREAD

**Issue by goldingn** [zoonproject/zoontutorials#34]
@Doi90 @lizhmartin @smwindecker I just rebased the zoonproject/zoontutorials repo (rewriting history to remove the cached files that were making everything slow). Before I did that, I merged the changes on [Doi90/temp](https://github.com/goldingn/zoontutorials/commit/76d667be2894edceb067b2bb7db9019647c1202b) and [lizhmartin/master](https://github.com/goldingn/zoontutorials/commit/7d630eeaa3c3d9c3a77c37d1d2da7a9e7a90ef23), so nothing that was pushed to github has been lost.

However, because I rewrote history, you can't just do the usual fetch & merge to get the changes (it'll let you, but that will undo my changes). Instead you each need to delete and recreate your local version of the repository. There are instructions below, but before you do those:

If you have any edits that are in your local repo (either committed or not), but *were not pushed to github*, you'll have to re-add them after replacing the repo. If you need to do that, just copy the files you changed to another location (i.e. outside the zoontutorials directory) before you delete your local zoontutorials repo. Then once you've replaced the repo with the instructions below, you can copy the files back and commit them.

Instructions to recreate your local copy of the repo:
1. delete your local zoontutorials directory
2. do: `git clone https://github.com/zoonproject/zoontutorials.git` in the directory *above* where you want the zoontutorials directory, to recreate it
3. do: `cd zoontutorials`
4. do: `git remote set-url origin https://github.com/<your username>/zoontutorials.git` (replacing `<your username>` with your github username)
5. do `git remote add upstream https://github.com/zoonproject/zoontutorials.git`
6. do `git push -f origin` to overwrite your origin repos

Let me know if you have any problems with this. Also, please comment on this issue once you're done and I can delete this issue when we're all in sync.

**Comment by Doi90** [comment]
Everything seems to have worked fine on my end

**Comment by goldingn** [comment]
Cool, yeah it looks good.

Only issue is you still have a temp branch on your GitHub fork, which is
out of date. Your best bet is just to delete that in GitHub. If you go to
Doi90/zoontutorials and click on the 'branches' button, you should see a
trash icon next to the temp branch.

**Comment by Doi90** [comment]
Should be fixed now?

**Comment by goldingn** [comment]
yep, all sorted!

**Comment by smwindecker** [comment]
Seems to have worked on my end.

**Comment by leehazel** [comment]
Done.

**Comment by goldingn** [comment]
Sweet, all sorted then!
