### ISSUE TITLE
add equation references/numbers

### ISSUE THREAD

**Issue by leehazel** [zoonproject/zoontutorials#45]
It's be good to be able to reference equations in text using a numerical reference, as per papers, theses.

**Comment by Doi90** [comment]
I imagine this could be as simple a fix as adding a (1) at the end of the formula code?

**Comment by leehazel** [comment]
I reckon there might be a more elegant way to do it in markdown code.

**Comment by Doi90** [comment]
Hhmm, I've found a couple of possibilities but they don't seem simple. Various combinations of latex/pandoc/CSS code. I'll try some out in the morning

**Comment by leehazel** [comment]
No worries. Didn’t mean to add to your to do, just putting it up so it gets done.

**Comment by goldingn** [comment]
I think this is fixed now
